source 'https://rubygems.org'

# Specify your gem's dependencies in db_export.gemspec
gemspec
gem 'mysql2'
gem 'rspec'
gem 'database_cleaner'
gem 'guard'
gem 'guard-rspec'
gem 'ccp_dbmodel', :path => '../gems/dbmodel'
gem 'rake'
gem 'activerecord', '3.2.8'
gem 'shoulda'
gem 'factory_girl'
gem 'faker'
gem 'database_cleaner'
gem 'highline'
gem 'spork'
gem 'prawn'
gem 'mail'
gem 'rubyzip'